name: Email HPE
description: ""

inputs:
  to:
    description: "Email address to send the email to"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v5
      with:
        to: ${{ inputs.to }}
        subject: "HPE Deployment Email"
        body: "This is a test email from the HPE deployment workflow."
