name: Test Email action

on:
  workflow_dispatch:

jobs:
  run-email-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Call the Action
        uses: ./.github/actions/hpe-email
